### PR TITLE
Fix some of types

### LINKED ISSUE #3117: Type checking error in GlassBR DD: `minThick`
Related to #3093 

```
`minThick` exposes ill-typed expressions!
  - ERROR: Both operands of an (in)equality (=/≠) must be of the same type. Received `Rational` & `Real`.
```

The error message is perhaps a bit misleading. It's checking the expression `sy minThick $= ...`, so there is an issue in typing expectation.

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/glassbr/lib/Drasil/GlassBR/DataDefs.hs#L61-L74

### LINKED ISSUE #3120: Type checking error in GlassBR DD: `lResistance`
Related to #3093 

```
`lResistance` exposes ill-typed expressions!
  - ERROR: Associative arithmetic operation expects all operands to be of the same expected type (Real).
    Received:
    - Rational
    - Real
    - Real
 ```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/glassbr/lib/Drasil/GlassBR/DataDefs.hs#L44-L60

### LINKED ISSUE #3125: Type checking error in SWHS DD: `htFusion`
Related to #3093 

```
`htFusion` exposes ill-typed expressions!
  - ERROR: Both operands of an (in)equality (=/≠) must be of the same type. Received `Rational` & `Real`.
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L131-L146

### LINKED ISSUE #3126: Type checking error in SWHS DD: `aspectRatio`
Related to #3093 

```
`aspectRatio` exposes ill-typed expressions!
  - ERROR: Both operands of an (in)equality (=/≠) must be of the same type. Received `Real` & `Rational`.
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L168-L175

### LINKED ISSUE #3127: Type checking error in SWHS DD: `wVol`
Related to #3093 

```
`wVol` exposes ill-typed expressions!
  - ERROR: Both operands of a subtraction must be the same numeric type. Received `Real` - `Rational`.
```
https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L50-L62

### LINKED ISSUE #3128: Type checking error in SWHS DD: `tankVol`
Related to #3093 

```
`tankVol` exposes ill-typed expressions!
  - ERROR: Associative arithmetic operation expects all operands to be of the same expected type (Real).
    Received:
    - Real
    - ERROR: Fractions/divisions should only be applied to the same numeric typed operands. Received `Rational` / `Real`.
    - Rational
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L66-L73

### LINKED ISSUE #3129: Type checking error in SWHS DD: `wMass`
Related to #3093 

```
`wMass` exposes ill-typed expressions!
  - ERROR: Associative arithmetic operation expects all operands to be of the same expected type (Real).
    Received:
    - Real
    - Rational
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L36-L46

### LINKED ISSUE #3130: Type checking error in SWHS DD: `meltFrac`
Related to #3093 

```
`meltFrac` exposes ill-typed expressions!
  - ERROR: Associative arithmetic operation expects all operands to be of the same expected type (Real).
    Received:
    - Rational
    - Real
````

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/swhs/lib/Drasil/SWHS/DataDefs.hs#L150-L164

### PR DESCRIPTION
**Pull request by JacquesCarette**
Closes #3128
Closes #3126 
Closes #3125
Closes  #3130
Closes  #3127
Closes  #3129
Closes  #3117
Closes  #3120

This changes most of the Rational to Real. 

There are also some commits wrt being able to make functions, but these are not used (yet).

### CODE REVIEW

File: code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs [hunk 1]
```diff
@@ -154,7 +154,7 @@ vectRotate = funcDef "vectRotate" [vV1, vV2] (Vect Rational)
     )
   ]
   
-vectUnrotate = funcDef "vectUnrotate" [vV1, vV2] (Vect Rational)
+vectUnrotate = funcDef "vectUnrotate" [vV1, vV2] (Vect Real)
```
Comment (balacij) [inline code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs:157]: Out of curiosity, were these changes automatically caught by the type-checker (or somewhere down the line), or did you extrapolate yourself?

File: code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs [hunk 2]
```diff
@@ -166,17 +166,17 @@ vectUnrotate = funcDef "vectUnrotate" [vV1, vV2] (Vect Rational)
...
+vectLengthSq = funcDef "vectLengthSq" [v_v] Real
   [
     FRet (FCall (funcUID vectDot) [v_v, v_v])
   ]
   
-vectLength = funcDef "vectLength" [v_v] Rational
+vectLength = funcDef "vectLength" [v_v] Real
   [
     FRet (Sqrt (FCall (funcUID vectLengthSq) [v_v]))
   ]
```
Comment (balacij) [inline code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs:177]: I don't quite understand why these are here. They all look like they should be explained somewhere outside of GamePhysics and imported here. Since they're all related to functionality of Vectors, they might really be part of a "standard library" that should be built for each example using vectors in any of its expressions.

**Review by balacij — APPROVED** [review]
Perfect! It looks like it closes many tickets too :smile:

File: code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs (hunk 1 above)
Comment (JacquesCarette) [reply code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs:157]: For this one, I extrapolated myself.

File: code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs (hunk 2 above)
Comment (JacquesCarette) [reply code/drasil-example/gamephysics/lib/Drasil/GamePhysics/DesignDec/Vector.hs:177]: Completely agree - please open an Issue for this.
