### PR TITLE
Fixed duplication error in ToS of GlassBR

### LINKED ISSUE #893: Duplication of terms in the Table of Symbols for GlassBR
This is a sub-issue originating from issue: #824

### PR DESCRIPTION
**Pull request by elwazana**
closes #893

### CODE REVIEW

File: code/drasil-example/Drasil/GlassBR/Unitals.hs [hunk 1]
```diff
@@ -191,8 +191,8 @@ sdy         = unitary "sdy" (nounPhraseSP "stand off distance (y-component)")
 sdz         = unitary "sdz" (nounPhraseSP "stand off distance (z-component)")
   (sub (eqSymb standOffDist) lZ) metre Real
 
-sd          = unitary "sd" (nounPhraseSP "stand off distance")
-  (eqSymb standOffDist) metre Real
+--sd          = unitary "sd" (nounPhraseSP "stand off distance")
```
Comment (szymczdm) [inline code/drasil-example/Drasil/GlassBR/Unitals.hs]: If this is going to be unused, it can be removed entirely.
