### PR TITLE
Fix `\brief` for Projectile

### LINKED ISSUE #3218: Projectile: Code: Fix \brief for doxygen
The [`\brief` tag](https://github.com/JacquesCarette/Drasil/blob/09365d7d1f5dc9b54e84a8d64cb601184456ea0c/code/stable/projectile/projectile_u_p_nol_u_wi_v_d/src/python/Projectile.py) in the generated `Projectile.py` file is currently a comment to the developers, as opposed to a comment to users of the code.  The current tag says "Contains the entire Projectile program."  We should fix this to provide the purpose of the program.  The purpose `\brief` should be "Efficiently and correctly predict whether a launched projectile hits its target."  Ideally the purpose here should come from the same source as for the README file (#3159) and the SRS.

### PR DESCRIPTION
**Pull request by hrzhuang**
Closes #3218

### CODE REVIEW

File: code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs [hunk 1]
```diff
@@ -154,7 +153,8 @@ concIns = assumptions ++ funcReqs ++ goals ++ nonfuncReqs
 -- Problem Description --
 -------------------------
 
--- Introduction of the Problem Description section derives from purp
+probDescIntro :: Sentence
+probDescIntro = S "efficiently" +:+ purp
```
Comment (samm82) [inline code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs:157]: Based on [Dr. Smith's comment](https://github.com/JacquesCarette/Drasil/pull/3248#issuecomment-1567400242) on #3248, I would remove this and just use `purp` instead of `probDescIntro`, since the "SRS doesn't define what we mean by efficient" and the "code doesn't do anything [specifically] to be efficient."

File: code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs [hunk 2]
```diff
@@ -214,4 +216,4 @@ physAndSfwrCons = do
         (inputs $ codeSpec g)
   return $ stringList [
     if not (any isPhysC cns) then "" else "physical constraints",
-    if not (any isSfwrC cns) then "" else "software constraints"]
\ No newline at end of file
+    if not (any isSfwrC cns) then "" else "software constraints"]
```
Comment (samm82) [inline code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs:219]: A minor thing, but it is convention to end files with a trailing newline.
```suggestion
    if not (any isSfwrC cns) then "" else "software constraints"]
    
```

**Review by samm82 — CHANGES_REQUESTED** [review]

File: code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs (hunk 1 above)
Comment (hrzhuang) [reply code/drasil-example/projectile/lib/Drasil/Projectile/Body.hs:157]: I think we should keep the "efficiently" based on Dr. Smith's comment on #3218 that "[he is] fine with keeping the non-functional requirements in the introduction." We also kept the non-functional requirements in the introduction for #3419.

File: code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs (hunk 2 above)
Comment (hrzhuang) [reply code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs:219]: It seems like there was already a trailing newline there and you added an additional one? Now there are two trailing newlines.

Comment (samm82) [reply code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs:219]: Hmm... my diff looks like there was a trailing line removed - I'll see what it looks like in the branch

Comment (samm82) [reply code/drasil-code/lib/Language/Drasil/Code/Imperative/Descriptions.hs:219]: Yes, you are right - my bad!

**Review by samm82 — APPROVED** [review]

**Review by smiths — APPROVED** [review]
The changes to stable look good to me.
