### PR TITLE
removes extra calls to mkDocDesc

### LINKED ISSUE #4426: Broken control flow for dealing with SRS document
So I was trying to get rid of the "bad" automation that adds input requirements automatically, i.e.
https://github.com/JacquesCarette/Drasil/blob/75dbc3f07ec51c6f4abdefc400c5a0e055ad72c6/code/drasil-docLang/lib/Drasil/Sections/Requirements.hs#L41-L45

But there's that call to `nub` there which is suspicious. It could be just "well, if someone adds the same requirement twice, don't worry about it". So I tried to take it out, just to see. What happens is that the *input requirements* get added twice!!!  So that `nub` is there to deal with that.

So I try something, out of curiousity: add a call to `trace` (from `Debug.Trace`) to let me see. And that's the big surprise: `fullReqs` does not get called twice, it gets called *four* times for all of SRS that use `FReqSub` !

### PR DESCRIPTION
**Pull request by JacquesCarette**
closes #4426 .

Some de-duplication between dplpend and sglpend snuck in as well.

### CODE REVIEW

File: code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs [hunk 1]
```diff
@@ -43,11 +44,15 @@ import Drasil.PDController.ODEs (pidODEInfo)
...
 
-srs :: Document
-srs = mkDoc mkSRS (S.forGen titleize phrase) fullSI
+sd  :: (System , DocDesc)
+sd = fillcdbSRS mkSRS si
 
+-- sigh, this is used by others
 fullSI :: System
-fullSI = fillcdbSRS mkSRS si
+fullSI = fst sd
```
Comment (balacij) [inline code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs:52]: Because you mentioned this on Discord, we can do:

```haskell
fullSI :: System
sd :: (System, DocDesc)
sd@(fullSI, _) = fillcdbSRS mkSRS si
```

But I'm not exactly a fan of that. The `fst` is more readable IMO.

File: code/drasil-example/template/lib/Drasil/Template/Body.hs [hunk 2]
```diff
@@ -20,22 +21,26 @@ import Data.Drasil.Citations
...
+sd  :: (System , DocDesc)
+sd = fillcdbSRS mkSRS si
 
+-- sigh, this is used by others
 fullSI :: System
-fullSI = fillcdbSRS mkSRS si
+fullSI = fst sd
+
+srs :: Document
+srs = mkDoc mkSRS (S.forGen titleize phrase) sd
```
Comment (balacij) [inline code/drasil-example/template/lib/Drasil/Template/Body.hs:31]: In subsequent work, we should abstract all of this duplicated blocks of code somewhere/somehow.

**Review by balacij — DISMISSED** [review]
LGTM!

**Review by balacij — APPROVED** [review]

File: code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs (hunk 1 above)
Comment (JacquesCarette) [reply code/drasil-example/pdcontroller/lib/Drasil/PDController/Body.hs:52]: Ah, that is the idiom that I was looking for! But happy enough not to use it.

File: code/drasil-example/template/lib/Drasil/Template/Body.hs (hunk 2 above)
Comment (JacquesCarette) [reply code/drasil-example/template/lib/Drasil/Template/Body.hs:31]: I agree - later.

**Comment by JacquesCarette** [comment]
Hmm, now that you've made some changes @balacij , that means you can't be an approver anymore! Maybe we can get @smiths to?

**Review by smiths — APPROVED** [review]
I approve the changes based on the quality of the discussion between @JacquesCarette and @balacij, rather than on expert knowledge of the changes on my part.  :smile:
