### PR TITLE
Reconcile _some_ conflicting/implicit knowledge about 'program' names during generation of various artifacts

### LINKED ISSUE #3565: PD Controller example is labelled as "PD_Controller" instead of "PDController" on website
I noticed this before but waited in case #3521 fixed this. The PD Controller example is called exactly that, space included:

https://github.com/JacquesCarette/Drasil/blob/8d5e8f8088bb87cd351d07f4104faae7fd49111f/code/drasil-example/pdcontroller/lib/Drasil/PDController/Concepts.hs#L17

However, it seems that on the website, this space is replaced with an underscore instead of just being omitted:
image
A consequence of this is that the links generated are incorrect:
image
Removing these underscores from the URL leads to the correct page:
image

Since this is the only example name with a space, I think there is likely a function that gets called at some point that replaces spaces with underscores, when they should just be omitted (at least in the use case of the website).

### PR DESCRIPTION
**Pull request by balacij**
Closes #3565
Builds on #3667

Instead of writing a description, I will annotate the code through a review. This PR is largely a follow-up to PR #3550 / Issue #3545.

### CODE REVIEW

File: code/Makefile [hunk 1]
```diff
@@ -179,9 +178,9 @@ BATCHTERM=dumb
 #--- Actual targets ---#
 ########################
 
-# Default `make` will just run examples and test them against stable.
-# See `test` target for more details.
-all: test ##@Examples Run examples and test against stable.
+# Default `make` will just run examples and test them against stable. See `test`
+# target for more details.
+all: test test_website ##@Examples Run examples and test against stable.
```
Comment (balacij) [inline code/Makefile:183]: `test_website` is a good target to add here because it makes `make all` and `make pr_ready` test the website against the stabilized website artifacts as well.

File: code/Makefile [hunk 2]
```diff
@@ -239,7 +238,7 @@ test: $(TEST_EXAMPLES) ##@Examples Run all examples and compare against the stab
 
 # First builds the website and then tests the generated contenst with those in
 # the stable-website folder.
-test_website: $(TEST_WEBSITE)
+test_website: $(TEST_WEBSITE) ##@Website Test freshly generated website against last known 'stable' copy.
```
Comment (balacij) [inline code/Makefile:241]: Adding a comment about the `test_website` target, for `make help`.

File: code/Makefile [hunk 3]
```diff
@@ -254,7 +253,7 @@ stabilize: $(STABILIZE_EXAMPLES) ##@Examples Overwrites the stable folder with u
 
 # First build the website, and then overwrite the contents in the stable-website
 # folder with currently generated ones.
-website_stabilize: $(STABILIZE_WEBSITE)
+website_stabilize: $(STABILIZE_WEBSITE) ##@Website Stabilize a freshly generated copy of the website artifacts.
```
Comment (balacij) [inline code/Makefile:256]: Again, adding a comment for another target, for `make help`.

File: code/drasil-docLang/lib/Drasil/DocumentLanguage.hs [hunk 4]
```diff
@@ -179,7 +178,7 @@ fillReferences dd si@SI{_sys = sys} = si2
     -- set new reference table in the chunk database
     chkdb2 = set refTable (idMap $ nub $ refsFromSRS ++ inRefs
       ++ map (ref.makeTabRef'.getTraceConfigUID) (traceMatStandard si) ++ secRefs -- secRefs can be removed once #946 is complete
-      ++ traceyGraphGetRefs (filter (not.isSpace) $ abrv sys) ++ map ref cites
+      ++ traceyGraphGetRefs (programName sys) ++ map ref cites
```
Comment (balacij) [inline code/drasil-docLang/lib/Drasil/DocumentLanguage.hs:181]: The first of many similar changes. `filter (not.isSpace)` is often applied to the names of our various 'programs' (case study abbreviations) to remove spaces from the name. The goal of the filter was to make the program names friendly to code and file-systems. So, instead, I made it default to the calculated program names, which now remove spaces instead of replacing them with underscores.

File: code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs [hunk 5]
```diff
@@ -187,10 +187,10 @@ traceyGraphPath :: String -> String -> String
 
 traceGFiles = ["avsa", "avsall", "refvsref", "allvsr", "allvsall"]
 traceGUIDs = map mkUid ["TraceGraphAvsA", "TraceGraphAvsAll", "TraceGraphRefvsRef", "TraceGraphAllvsR", "TraceGraphAllvsAll"]
-traceyGraphPaths ex = map (\x -> resourcePath ++ map toLower (filter (not.isSpace) ex) ++ "/" ++ x ++ ".svg") traceGFiles
-traceyGraphGetRefs ex = map makeFigRef' traceGUIDs ++ zipWith (\x y -> Reference (x +++. "Link") (URI y) (shortname' $ S $ show x)) traceGUIDs (traceyGraphPaths $ map toLower $ filter (not.isSpace) ex)
+traceyGraphPaths ex = map (\x -> resourcePath ++ map toLower ex ++ "/" ++ x ++ ".svg") traceGFiles
+traceyGraphGetRefs ex = map makeFigRef' traceGUIDs ++ zipWith (\x y -> Reference (x +++. "Link") (URI y) (shortname' $ S $ show x)) traceGUIDs (traceyGraphPaths $ map toLower ex)
 -- for actual use in creating the graph figures
-traceyGraphPath ex f = resourcePath ++ map toLower (filter (not.isSpace) ex) ++ "/" ++ f ++ ".svg"
```
Comment (balacij) [inline code/drasil-docLang/lib/Drasil/DocumentLanguage/TraceabilityGraph.hs:193]: Note: `filter (not.isSpace)` on abbreviations is only 1 issue of impromptu formatting of case study names. The `map toLower` is another issue, which occurs as often.

File: code/drasil-website/lib/Drasil/Website/CaseStudy.hs [hunk 6]
```diff
@@ -59,7 +59,7 @@ data CaseStudy = CS {
 -- so we take the naming scheme from there.
 mkCaseStudy :: Example -> [CaseStudy]
 mkCaseStudy E{choicesE = []} = []
-mkCaseStudy E{sysInfoE = si@SI{_sys = sys}, choicesE = [x]} = [CS{sysInfoCS = si, progName = S $ programName sys, choicesCS = x}]
+mkCaseStudy E{sysInfoE = si@SI{_sys = sys}, choicesE = [x]} = [CS{sysInfoCS = si, progName = S $ abrv sys, choicesCS = x}]
```
Comment (balacij) [inline code/drasil-website/lib/Drasil/Website/CaseStudy.hs:62]: This was one of the main issues with the website display names. 

Previously, `programName` replaced spaces with underscores. Now it removes them altogether. Hence, keeping `programName` (as done in @3550) here wouldn't work. So, since we're already displaying the human-friendly abbreviation for the case study, we should be free to include our spaces, so we revert to using `abrv`.

File: code/drasil-website/lib/Drasil/Website/Example.hs [hunk 7]
```diff
@@ -79,16 +79,16 @@ fullExList codePth srsDoxPth = Enumeration $ Bullet $ map (, Nothing) (allExampl
...
 -- | Display the points for generated documents and call 'versionList' to display the code.
 individualExList :: Example -> [ItemType]
 -- No choices mean no generated code, so we do not need to display generated code and thus do not call versionList.
 individualExList E{sysInfoE = SI{_sys = sys}, choicesE = [], codePath = srsP} = 
-  [Flat $ S (programName sys ++ "_SRS") +:+ namedRef (getSRSRef srsP "html" $ programName sys) (S "[HTML]") +:+ namedRef (getSRSRef srsP "pdf" $ programName sys) (S "[PDF]")]
+  [Flat $ S "SRS:" +:+ namedRef (getSRSRef srsP "html" $ programName sys) (S "[HTML]") +:+ namedRef (getSRSRef srsP "pdf" $ programName sys) (S "[PDF]")]
 -- Anything else means we need to display program information, so use versionList.
 individualExList ex@E{sysInfoE = SI{_sys = sys}, codePath = srsP} = 
-  [Flat $ S (programName sys ++ "_SRS") +:+ namedRef (getSRSRef srsP "html" $ programName sys) (S "[HTML]") +:+ namedRef (getSRSRef srsP "pdf" $ programName sys) (S "[PDF]"),
+  [Flat $ S "SRS:" +:+ namedRef (getSRSRef srsP "html" $ programName sys) (S "[HTML]") +:+ namedRef (getSRSRef srsP "pdf" $ programName sys) (S "[PDF]"),
```
Comment (balacij) [inline code/drasil-website/lib/Drasil/Website/Example.hs:91]: I was going to replace this with an `abrv sys ++ "SRS"`, resulting in `PD Controller_SRS [HTML] [PDF]` on the website, but I found it odd to keep the `_`, so I removed that. Afterwards, I found the name repetition too frequent in such a small area, so I just opted to remove the abbreviation altogether.

File: code/drasil-website/lib/Drasil/Website/Example.hs [hunk 8]
```diff
@@ -208,15 +208,18 @@ getSRSRef path sufx ex = makeURI refUID (getSRSPath path (map toLower sufx) ex)
 -- | Get the paths of where each reference exist for SRS files. Some example abbreviations have spaces,
 -- so we just filter those out. The suffix should only be either html or pdf.
 getSRSPath :: FilePath -> String -> String -> FilePath
-getSRSPath path sufx ex = path ++ map toLower (filter (not.isSpace) ex)
-  ++ "/SRS/srs/" ++ filter (not.isSpace) ex ++ "_SRS." ++ map toLower sufx
+getSRSPath path sufx ex = 
+  path
+  ++ map toLower ex -- FIXME: The majority of these `map toLower`s are implicit knowledge!!!
```
Comment (balacij) [inline code/drasil-website/lib/Drasil/Website/Example.hs:213]: The `map toLower`s happen quite often!

File: code/stable-website/index.html [hunk 9]
```diff
@@ -236,24 +236,24 @@ <h1>Generated Examples</h1>
...
               </li>
               <li>
                 Generated Code:
                 <ul class="list">
                   <li>
-                    PD_Controller <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pd_controller/src/python">[Python]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pd_controller/src/csharp">[C Sharp]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pd_controller/src/java">[Java]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pd_controller/src/cpp">[C++]</a>
+                    PDController <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pdcontroller/src/python">[Python]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pdcontroller/src/csharp">[C Sharp]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pdcontroller/src/java">[Java]</a> <a href="https://github.com/JacquesCarette/Drasil/tree/master/code/stable/pdcontroller/src/cpp">[C++]</a>
```
Comment (balacij) [inline code/stable-website/index.html:248]: Here is the resultant 'actual' fix. Note that the name shown here doesn't align with the name shown on line 239!

Why? Well, the top-level `<li>` nodes show the main abbreviation, but this is the name of the final 'executable program/project/case study, taking into consideration the choices'. Following in line with how the other projects (including the multi-src Projectile case study in mind), we use the name of the 'executable program', left uppercase. 

If we wanted to make this name lowercase, we can, similar to how this name is done everywhere else. If we wanted to avoid putting the name of the case study here again, we can (I would prefer this, but I thought I was pushing the boundary of this PR too much now). If we want to include the space, we can. Ultimately, I didn't quite know what name we wanted here, but finally, it notes the 'real' issue here:

We have impromptu naming and calculation of things everywhere. This PR is specifically about the name of `PD Controller` and how we propagate it, but us having the freedom of Haskell is a bit of a double-edged sword here, whereby we can have impromptu temporary code placed anywhere that breaks uniformity and actual knowledge captured for a specific 'fix'.

File: code/stable/pdcontroller/src/cpp/Makefile [hunk 10]
```diff
@@ -12,18 +12,18 @@ endif
 
 # Generated by Drasil v0.1-alpha
 
-# Project Name: PD_Controller
+# Project Name: PDController
```
Comment (balacij) [inline code/stable/pdcontroller/src/cpp/Makefile:15]: Again, similar to the above comment, using the same uniform naming scheme that we use in URIs, etc.

**Comment by balacij** [comment]
Ultimately, the solution isn't complex, but it does rely on the abbreviations of our case studies and how we want to translate them to 'code' artifacts.

File: code/drasil-website/lib/Drasil/Website/CaseStudy.hs (hunk 6 above)
Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/CaseStudy.hs]: I reverted this one to keep continuity with the other names in the case studies table containing the final case studies project folder name, but the blurb of discussion is still good.

File: code/drasil-website/lib/Drasil/Website/Example.hs (hunk 8 above)
Comment (samm82) [reply code/drasil-website/lib/Drasil/Website/Example.hs:213]: Do these show up as a redundancy to enforce them being lowercase, or is there something that is being made lowercase in multiple places (instead of just being made lowercase at its definition)?

Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/Example.hs:213]: Ah, that's a good catch. I completely forgot to address why they appear.

It does not appear to be a redundancy to enforce them being lowercase. I don't really think we should _need_ nearly any sort of redundancy, since we generate through staging.

These `map toLower`s applied to our case study names is to relate to the things that were named after our project folder names in the `code/drasil-example` folder -- they are all lowercase. We should probably figure out a better way of handling external resources internally, preferrably reading them in externally and having an external dictionary that's passed to/compiled into Drasil.

Comment (samm82) [reply code/drasil-website/lib/Drasil/Website/Example.hs:213]: I feel like this could be related to how we've been handling paths to Projectile-related files (since it uses design variabilities that introduce another directory level) and figuring out how to handle this in the long term 🤔

Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/Example.hs:213]: Yep, it definitely is. We might need to do another pass at cleaning this up.

Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/Example.hs:213]: Also related to #3557

File: code/drasil-gen/lib/Language/Drasil/Dump.hs [hunk 11]
```diff
@@ -16,22 +16,25 @@ import Database.Drasil (traceTable, refbyTable)
...
+
 type Path = String
 type TargetFile = String
 
 -- | For debugging purposes, if the system has a `DEBUG_ENV` environment
 --   variable set to anything, we can dump the chunk maps in a system to the
 --   host system.
-dumpEverything :: SystemInformation -> Path -> IO ()
-dumpEverything si p = do
+dumpEverything :: SystemInformation -> PrintingInformation -> Path -> IO ()
```
Comment (JacquesCarette) [inline code/drasil-gen/lib/Language/Drasil/Dump.hs:28]: Why is this PR dependent on the one that deals with dumping debug information? These two should be separate. Especially as I've got qualms about that one, which will now delay this one!

File: code/drasil-website/lib/Drasil/Website/Example.hs [hunk 12]
```diff
@@ -79,16 +79,16 @@ fullExList codePth srsDoxPth = Enumeration $ Bullet $ map (, Nothing) (allExampl
 allExampleList :: [Example] -> [ItemType]
 allExampleList = map (\x -> Nested (nameAndDesc x) $ Bullet $ map (, Nothing) (individualExList x))
   where
-    nameAndDesc E{sysInfoE = SI{_sys = sys, _purpose = purp}} = S (programName sys) +:+ S " - To" +:+. head purp
+    nameAndDesc E{sysInfoE = SI{_sys = sys, _purpose = purp}} = S (abrv sys) +:+ S " - To" +:+. head purp
```
Comment (JacquesCarette) [inline code/drasil-website/lib/Drasil/Website/Example.hs:82]: Isn't this a regression? We want to use `abrv` less, and `programName` was a step in that direction.

**Review by JacquesCarette — CHANGES_REQUESTED** [review]
Please disentangle these two PRs.

File: code/drasil-gen/lib/Language/Drasil/Dump.hs (hunk 11 above)
Comment (balacij) [reply code/drasil-gen/lib/Language/Drasil/Dump.hs]: Rebased!

File: code/drasil-website/lib/Drasil/Website/Example.hs (hunk 12 above)
Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/Example.hs:82]: Isn't this reverting a regression instead? `abrv` carries the actual abbreviation of the `PD Controller` project. `programName` calculates what a 'valid program name' would be given the abbreviation (replacing a space with an underscore).

Comment (JacquesCarette) [reply code/drasil-website/lib/Drasil/Website/Example.hs:82]: Ok, for this one,  I think you're right.

**Review by JacquesCarette — APPROVED** [review]

File: code/drasil-website/lib/Drasil/Website/Example.hs (hunk 7 above)
Comment (samm82) [reply code/drasil-website/lib/Drasil/Website/Example.hs:91]: One thing I just noticed: should this line (and any other related lines) be using our abbreviations for "SRS", "HTML", etc.?

Comment (balacij) [reply code/drasil-website/lib/Drasil/Website/Example.hs:91]: Aha! They definitely shouldn't be using the raw `String` versions, so I think that's a great big "yes" to reduce duplication :smile:

**Review by JacquesCarette — APPROVED** [review]
