### PR TITLE
3418 fix Drasil Logo path on ReadMes - Updated

### LINKED ISSUE #3418: Fix Drasil image path in READMEs
It seems like the path to the Drasil logo (?) from the READMEs is incorrectly generated; the path should have one extra "../" to go up one more directory.

## Relevant HTML code in README:
https://github.com/JacquesCarette/Drasil/blob/f003baf9c65a28c28a58b4aa5010b73cec672203/code/stable/projectile/projectile_c_p_nol_b_u_v_d/src/python/README.md?plain=1#L29-L31

## What this looks like:
image

## Clicking on the image link:
image

## What the path should be:
image

### PR DESCRIPTION
**Pull request by harmanpreet-sagar**
Closes #3418: Fix Drasil image path in READMEs. Changes made to CreateMd.hs, WriteReadMe.hs, Document.hs and the projectile example in stable in order to update the broken image link in the Projectile READMEs.

### CODE REVIEW

**Comment by harmanpreet-sagar** [comment]
This is a temporary solution. I will open up an issue that would explore creating a much more permanent solution which includes having records of the number of folders that have been entered and then referencing the record in order to obtain a `FilePath` prefix for any and all filepaths.

File: code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs [hunk 1]
```diff
@@ -96,24 +97,15 @@ addListToTuple _ _ = []
...
+
 -- | End section.
-endNote :: [String] -> Doc
-endNote auth = text "*This README is a software artifact generated by Drasil.*" <> doubleSep <> license (listToDoc auth) <> doubleSep <> drasilImage 
+endNote :: Int -> [String] -> Doc
+endNote num auth = text "*This README is a software artifact generated by Drasil.*" <> doubleSep <> license (listToDoc auth) <> doubleSep <> drasilImage num
 
 -- | Section seperators.
-secSep, contSep, doubleSep, bkQuote, bkQuote3 :: Seperator
+secSep, doubleSep, bkQuote, bkQuote3 :: Seperator
```
Comment (samm82) [inline code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs:106]: How much of a change would it be to change `Seperator` to `Separator` to fix the typo throughout the code/comments? Should it be a separate PR or is it simple enough to do it here?

File: code/drasil-code/lib/Language/Drasil/Choices.hs [hunk 2]
```diff
@@ -38,7 +38,9 @@ data Choices = Choices {
   -- | Constraint violation behaviour. Exception or Warning.
   srsConstraints :: Constraints,
   -- | List of external libraries what to utilize 
-  extLibs :: [ExtLib]
+  extLibs :: [ExtLib],
+  -- | Number of folders to go up in order to obtain the image
+  folderVal :: Int
```
Comment (samm82) [inline code/drasil-code/lib/Language/Drasil/Choices.hs:43]: I think the original intent of the design was that there would be separate record type passed when generating code that would be responsible for specifying the environment instead of adding it to the `Choices` record here - I'm honestly not sure how important this distinction is at this point so I'm going to defer this to @JacquesCarette

File: code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs [hunk 3]
```diff
@@ -96,24 +97,15 @@ addListToTuple _ _ = []
...
-alignImage :: FilePath -> Doc
-alignImage img = text "<p align=\"center\">" <>
-  contSep <> text ("<img src=\"" ++ img ++ "\" alt=\"Drasil Tree\" width=\"200\" />")
-  <> contSep <> text "</p>"
+
 -- | End section.
-endNote :: [String] -> Doc
-endNote auth = text "*This README is a software artifact generated by Drasil.*" <> doubleSep <> license (listToDoc auth) <> doubleSep <> drasilImage 
+endNote :: Int -> [String] -> Doc
+endNote num auth = text "*This README is a software artifact generated by Drasil.*" <> doubleSep <> license (listToDoc auth) <> doubleSep <> drasilImage num
```
[the remark this answers is not in the document]
Comment (harmanpreet-sagar) [reply code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs:103]: I will change that right now!

File: code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs (hunk 1 above)
Comment (harmanpreet-sagar) [reply code/drasil-printers/lib/Language/Drasil/Markdown/CreateMd.hs:106]: It shouldn't be much work. It just needs to be fixed in 4 places I believe so I think we can do it in this PR itself.

File: code/drasil-code/lib/Language/Drasil/Choices.hs (hunk 2 above)
Comment (harmanpreet-sagar) [reply code/drasil-code/lib/Language/Drasil/Choices.hs:43]: I was under the impression that I needed to submit a fix for the `ReadMe`s right now and that the creation of the record would be a separate much bigger issue which is why I created issue #3468. @JacquesCarette Do you think that I should look at creating a record for this PR itself or should the creation of the record be a separate issue?

Comment (samm82) [reply code/drasil-code/lib/Language/Drasil/Choices.hs:43]: Oh I see - I didn't see that issue! Disregard this then lol

**Review by samm82 — APPROVED** [review]
Thanks for pointing out that other issue you created! 😅

**Review by JacquesCarette — APPROVED** [review]
