### PR TITLE
Fix a bug in typechecker and some types in SSP

### LINKED ISSUE #3106: Type checking error in ssp EqModel: nrmShrFor
Related to #3093, similar to #3105 

```
`nrmShrForIM` exposes ill-typed expressions!
  - List accessor expects a list/vector
```

https://github.com/JacquesCarette/Drasil/blob/0a240c0231b6f737011bc090962ae1925fbc83e2/code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs#L374-L388

### PR DESCRIPTION
**Pull request by JacquesCarette**
But there are many more left!  Also, remove some awful hacks, but leave in place at least one hack.

Fixes #3106 , #3107 , #3105 .

### CODE REVIEW

File: code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs [hunk 1]
```diff
@@ -605,7 +615,8 @@ crtSlpIdQD = mkQuantDef fsMin crtSlpIdExpr
 crtSlpIdExpr :: Expr
 crtSlpIdExpr = apply minFunction [sy slopeDist,
```
Comment (balacij) [inline code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs:616]: Out of curiosity, what needs to happen to make this right?

**Review by balacij — APPROVED** [review]

**Comment by balacij** [comment]
image

The rendering of characters is noticeably different with this one too.

File: code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs (hunk 1 above)
Comment (JacquesCarette) [reply code/drasil-example/ssp/lib/Drasil/SSP/IMods.hs:616]: I think what this "function" is supposed to do is to implement lots of the checks that are in the words that come with this instance model. Not sure what it is really supposed to return.
