### PR TITLE
Fix bibliography hyperlinks

### LINKED ISSUE #4046: SRS HTML: Bib references use text labels that the bibliography does not show
I noticed a small issue with Projectile's SRS:
* In [GD:rectVel](https://jacquescarette.github.io/Drasil/examples/projectile/SRS/HTML/Projectile_SRS.html#GD:rectVel), we link to `hibbeler2004`.
* https://jacquescarette.github.io/Drasil/examples/projectile/SRS/HTML/Projectile_SRS.html#hibbeler2004 links to an item that isn't called `hibbeler2004`, but `[1]`.

Conventionally, a [`dt` and `dd` HTML tag pair](https://www.w3schools.com/tags/tag_dd.asp) is used to build lists of term/description entry-like. Alternatively, tables work too, but that would be unconventional for a bibliography.

For example
```html
<dt id="drasil"><b>[Drasil2021]</b></dt> <dd>
Carette, J., Smith, S., Szymczak, D., Balaci, J., MacLachlan, B., Niazi, M., Crawford, S., Scime, D., Chen, D., Hunt, A., Wu, T., Bilal, M., & Bosman, B. (2021). Drasil (Version v0.1-alpha) [Computer software]. https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha
</dd>

<dt id="drasil"><b>[Drasil2022]</b></dt> <dd>
Carette, J., Smith, S., Szymczak, D., Balaci, J., MacLachlan, B., Niazi, M., Crawford, S., Scime, D., Chen, D., Hunt, A., Wu, T., Bilal, M., & Bosman, B. (2021). Drasil (Version v0.1-alpha) [Computer software]. https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha
</dd>
```

Generates:
<dt id="drasil"><b>[Drasil2021]</b></dt> <dd>
Carette, J., Smith, S., Szymczak, D., Balaci, J., MacLachlan, B., Niazi, M., Crawford, S., Scime, D., Chen, D., Hunt, A., Wu, T., Bilal, M., & Bosman, B. (2021). Drasil (Version v0.1-alpha) [Computer software]. https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha
</dd>

<dt id="drasil"><b>[Drasil2022]</b></dt> <dd>
Carette, J., Smith, S., Szymczak, D., Balaci, J., MacLachlan, B., Niazi, M., Crawford, S., Scime, D., Chen, D., Hunt, A., Wu, T., Bilal, M., & Bosman, B. (2021). Drasil (Version v0.1-alpha) [Computer software]. https://github.com/JacquesCarette/Drasil/tree/v0.1-alpha
</dd>

<br>
<br>

Note: with a little bit of CSS stylization, a list of dt/dd's can look nicer. e.g., indenting the `dd` (e.g., `margin-left: 20px;`) should be enough to make this list more presentable.

### PR DESCRIPTION
**Pull request by jackwyand**
Closes #4046 (based on [this comment](https://github.com/JacquesCarette/Drasil/pull/4056#discussion_r2083239546))
Visually the output is the same, however I cleaned up the code a bit. Instead of having a new function `descWrap` I just generalized `refwrap` to work with different tags rather than just div to avoid repeating ourselves as much.

Also, instead of having `reference-label` attached to the list items, I realized it was not actually needed and just reverted to the old ids to fix the hyperlinks.

### CODE REVIEW

File: code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs [hunk 1]
```diff
@@ -130,8 +131,13 @@ descWrap :: [String] -> Doc -> Doc -> Doc
 descWrap = flip (wrapGen Class "dt")
 
 -- | Helper for wrapping divisions or sections.
+refwrap' :: Maybe String -> Doc -> Doc -> Doc
+refwrap' a = flip (wrapGen Id tag) [""]
+  where
+    tag = fromMaybe "div" a
```
Comment (JacquesCarette) [inline code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs:137]: `fromMaybe` is a Haskell design smell -- please use `maybe` instead.

**Review by JacquesCarette — CHANGES_REQUESTED** [review]
Why is there an empty `code/Doc` file?

File: code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs (hunk 1 above)
Comment (balacij) [reply code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs:137]: This function definition is also a bit confusing. What are the arguments given to it? "Wrapping" node type, body, ...?

**Review by JacquesCarette — APPROVED** [review]

File: code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs [hunk 2]
```diff
@@ -131,10 +130,11 @@ descWrap :: [String] -> Doc -> Doc -> Doc
 descWrap = flip (wrapGen Class "dt")
 
 -- | Helper for wrapping divisions or sections.
+-- | Arguments: Wrapper text, attribute value, body text
```
Comment (balacij) [inline code/drasil-printers/lib/Language/Drasil/HTML/Helpers.hs:133]: Thank you for adding the note! I'm just going to be pedantic with one thing: "Wrapper text" -> "Wrapper element type/tag (e.g., p, div, a)" is a bit better.

**Review by balacij — APPROVED** [review]

**Comment by jackwyand** [comment]
Since these changes have been approved am I permitted to merge this? Or is that something only @JacquesCarette can do? Same question for #4050.

**Comment by JacquesCarette** [comment]
The contributor's guide should mention this: authors of a PR should generally not merge their own PRs. We prefer to have 2 people review a PR, and then usually the second reviewer triggers the merge.

Since @balacij didn't, I will do so now.
